### ISSUE TITLE
File content randomly truncated in large projects

### ISSUE THREAD

**Issue by mgilfillan** [browserify/module-deps#162]
When using browserify on a large project we regularily see errors such as:
`Parse Error: Line 233: Unexpected end of input while parsing file: ...`

The errors don't occur in a consistent file or line, the content of the file is truncated seemingly randomly.

Having investigated the issue we've tracked it down to the following in `Deps.prototype.readFile`:
```javascript
var rs = fs.createReadStream(file, {
    encoding: 'utf8',
});
```

If we increase the high water mark option the issue goes away:
``` javascript
var rs = fs.createReadStream(file, {
    encoding: 'utf8',
    highWaterMark: 1024 * 1024,
});
```

Note that the default high water mark is `64 * 1024` so this is a substantial increase. We haven't tested to see if a smaller value would also supress the issue.

I don't believe this the best solution for the problem but I don't have enough insight into the project to know why the issue may be happening or a better way to resolve it.

I'm happy to create a pull request with this change if you'd like.

**Comment by goto-bus-stop** [comment]
Does that error have a stack trace? I would _guess_ that it is inside a buggy transform, that's trying to parse a _chunk_ of a file instead of the entire file.

**Comment by mgilfillan** [comment]
```
Parse Error: Line 101: Unexpected end of input while parsing file: C:\Users\micha\Projects\eotw-2019\src\js\QuoteForm.js while parsing file: C:\Users\micha\Projects\eotw-2019\src\js\QuoteForm.js Error: Parse Error: Line 101: Unexpected end of input while parsing file: C:\Users\micha\Projects\eotw-2019\src\js\QuoteForm.js
    at throwError (C:\Users\micha\Projects\eotw-2019\node_modules\jstransform\node_modules\esprima-fb\esprima.js:2818:21)
    at throwUnexpected (C:\Users\micha\Projects\eotw-2019\node_modules\jstransform\node_modules\esprima-fb\esprima.js:2850:13)
    at expect (C:\Users\micha\Projects\eotw-2019\node_modules\jstransform\node_modules\esprima-fb\esprima.js:2889:13)
    at parseFunctionSourceElements (C:\Users\micha\Projects\eotw-2019\node_modules\jstransform\node_modules\esprima-fb\esprima.js:5787:9)
    at parseConciseBody (C:\Users\micha\Projects\eotw-2019\node_modules\jstransform\node_modules\esprima-fb\esprima.js:5727:20)
    at parseArrowFunctionExpression (C:\Users\micha\Projects\eotw-2019\node_modules\jstransform\node_modules\esprima-fb\esprima.js:4116:16)
    at parseAssignmentExpression (C:\Users\micha\Projects\eotw-2019\node_modules\jstransform\node_modules\esprima-fb\esprima.js:4211:24)
    at parseSpreadOrAssignmentExpression (C:\Users\micha\Projects\eotw-2019\node_modules\jstransform\node_modules\esprima-fb\esprima.js:3637:16)
    at parseArguments (C:\Users\micha\Projects\eotw-2019\node_modules\jstransform\node_modules\esprima-fb\esprima.js:3604:23)
    at parseLeftHandSideExpressionAllowCall (C:\Users\micha\Projects\eotw-2019\node_modules\jstransform\node_modules\esprima-fb\esprima.js:3686:24)
```

We're using browserify with the following plugins:
-  `jsx-transform`
- `babelify`
- `@babel/preset-env`
- `@babel/plugin-transform-proto-to-assign`
- `factor-bundle`

After running the gulp file a few times it appears the error is always being thrown within the `esprima-fb` library but this is likely because it is just the first plugin to process the javascript.

We have ourselves tested adding a custom transformer and can confirm that it gets a truncated copy of the source code rather than the full file.

**Comment by goto-bus-stop** [comment]
Does it reliably happen with that file? Are you allowed to share that file? If not, how large is it?

**Comment by mgilfillan** [comment]
It happens reliably, but not in the same file and not in the same location each time.

I've actually found the [offending code](https://github.com/alexmingoia/jsx-transform/blob/master/lib/jsx.js#L170) in the `jsx-transform` plugin. It was incorrectly operating on the chunk rather than the complete file.

I'm going to submit a pull request to that project to fix the issue. Thanks for you help though.
